/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package store;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import static store.Product.tblData;

/**
 *
 * @author mangg
 */
public class detailRiwayatTrx extends javax.swing.JDialog {

    public static String kodetrx;

    /**
     * Creates new form detailRiwayatTrx
     */
    public detailRiwayatTrx(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        showTable(kodetrx);
        showDetail(kodetrx);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtdUser = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtdDate = new javax.swing.JTextField();
        txtdIdTrx = new javax.swing.JTextField();
        txtdtotalHarga = new javax.swing.JTextField();
        txtduang = new javax.swing.JTextField();
        txtdKembali = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetailRiwayat = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(221, 238, 238));
        jPanel1.setPreferredSize(new java.awt.Dimension(864, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/icon/pc.de-hamburg-icon-pack/16x16/print.png"))); // NOI18N
        jButton2.setText("Print Transaksi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama  :");

        txtdUser.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 401, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtdUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(221, 238, 238));
        jPanel2.setPreferredSize(new java.awt.Dimension(864, 150));

        txtdDate.setEditable(false);
        txtdDate.setSelectedTextColor(new java.awt.Color(242, 242, 242));

        txtdIdTrx.setEditable(false);
        txtdIdTrx.setSelectedTextColor(new java.awt.Color(242, 242, 242));

        txtdtotalHarga.setEditable(false);
        txtdtotalHarga.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtdtotalHarga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtduang.setEditable(false);
        txtduang.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtduang.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtduang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtduangKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtduangKeyReleased(evt);
            }
        });

        txtdKembali.setEditable(false);
        txtdKembali.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtdKembali.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setText("Kembali :");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Uang :");

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setText("Total :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(551, 551, 551)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdIdTrx, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdDate, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtduang, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtdtotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtdtotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtdDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtduang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdIdTrx, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(221, 238, 238));
        jPanel3.setPreferredSize(new java.awt.Dimension(50, 485));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel4.setBackground(new java.awt.Color(221, 238, 238));
        jPanel4.setPreferredSize(new java.awt.Dimension(50, 485));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        tblDetailRiwayat.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tblDetailRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDetailRiwayat.setPreferredSize(new java.awt.Dimension(300, 50));
        tblDetailRiwayat.setRowHeight(25);
        jScrollPane1.setViewportView(tblDetailRiwayat);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            String file = "/home/mangg/NetBeansProjects/Printing-Store/src/store/report1.jrxml";
            
          
            HashMap param = new HashMap();
            
            for (int i = 0; i < tblDetailRiwayat.getRowCount(); i++) {
                param.put("id_brg", "i");
            }
            param.put("kodetransaksi", txtdIdTrx.getText());
            param.put("total", txtdtotalHarga.getText());
            param.put("uang", txtduang.getText());
            param.put("kembali", txtdKembali.getText());
            param.put("tanggal", txtdDate.getText());


            this.setVisible(false);
            JasperReport JRpt = JasperCompileManager.compileReport(file);
            JasperPrint print = JasperFillManager.fillReport(JRpt,param,Koneksi.konekKeDB());
            JasperViewer.viewReport(print, false);
            
        }catch(JRException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtduangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtduangKeyPressed

    }//GEN-LAST:event_txtduangKeyPressed

    private void txtduangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtduangKeyReleased

    }//GEN-LAST:event_txtduangKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detailRiwayatTrx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detailRiwayatTrx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detailRiwayatTrx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detailRiwayatTrx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                detailRiwayatTrx dialog = new detailRiwayatTrx(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblDetailRiwayat;
    private static javax.swing.JTextField txtdDate;
    public javax.swing.JTextField txtdIdTrx;
    private javax.swing.JTextField txtdKembali;
    private javax.swing.JTextField txtdUser;
    private javax.swing.JTextField txtdtotalHarga;
    private javax.swing.JTextField txtduang;
    // End of variables declaration//GEN-END:variables

    public static void showTable(String kodetrx) {
        try {
            Object[][] data = null;
            Object[] header = {"ID", "KODE", "NAMA", "HARGA", "QTY", "KET"};
            DefaultTableModel model = new DefaultTableModel(data, header) {
                public boolean isCellEditable(int row, int column) {
                    return false;//This causes all cells to be not editable
                }
            };
            tblDetailRiwayat.setModel(model);
            int nomor = 0;
            //load data from DB
            Connection koneksi = Koneksi.konekKeDB();
            Statement st = koneksi.createStatement();
            String query = "SELECT dt.kode_trx, dt.kode_barang, p.nama, p.harga, dt.qty, p.harga*dt.qty AS jumlah "
                    + "FROM detail_transaction AS dt INNER JOIN product AS p "
                    + "ON dt.kode_barang = p.kode WHERE dt.kode_trx = '" + kodetrx + "';";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                String kodeBarang = rs.getString("kode_barang");
                String namaBarang = rs.getString("nama");
                int hargaB = rs.getInt("harga");
                int qtyB = rs.getInt("qty");
                String jumlahB = rs.getString("jumlah");

                nomor++;
                Object[] d = {nomor, kodeBarang, namaBarang, hargaB, qtyB, jumlahB};
                model.addRow(d);
            }
            koneksi.close();
        } catch (SQLException e) {

        }
    }

    private void showDetail(String kodetrx) {
        String namaUser = "";
        String kodeTransaksi = "";
        String total = "";
        String uang = "";
        String kembali = "";
        String tanggal = "";

        try {
            //load data from DB
            Connection koneksi = Koneksi.konekKeDB();
            Statement st = koneksi.createStatement();
            String query = "SELECT * FROM transactionQ WHERE kode_tr = '" + kodetrx + "'";
            ResultSet rs = st.executeQuery(query);

            int nomor = 0;
            while (rs.next()) {
                namaUser = rs.getString("kode_user");
                kodeTransaksi = rs.getString("kode_tr");
                total = rs.getString("total");
                uang = rs.getString("uang");
                kembali = rs.getString("kembali");
                tanggal = rs.getString("created_at");

            }

            koneksi.close();
        } catch (SQLException e) {

        }

        txtdUser.setText(showUser(Integer.parseInt(namaUser)));
        txtdIdTrx.setText(kodeTransaksi);
        txtdtotalHarga.setText(total);
        txtduang.setText(uang);
        txtdKembali.setText(kembali);
        txtdDate.setText(tanggal);
    }

    private String showUser(int user) {
        String nama = "";
        try {
            //load data from DB
            Connection koneksi = Koneksi.konekKeDB();
            Statement st = koneksi.createStatement();
            String query = "SELECT * FROM users WHERE id = " + user + ";";
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                nama = rs.getString("nama");
            }

            koneksi.close();
        } catch (SQLException e) {

        }

        return nama;
    }
}
