/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package store;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author mangg
 */
public class keranjangProduct extends javax.swing.JDialog {

    /**
     * Creates new form keranjangProduct
     */
    public keranjangProduct(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Keranjang Produk");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnSimpanTrx = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmbUser = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txttotalHarga = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtuang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtKembali = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIdTrx = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKeranjang = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(221, 238, 238));
        jPanel1.setPreferredSize(new java.awt.Dimension(781, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/icon/pc.de-hamburg-icon-pack/16x16/print.png"))); // NOI18N
        jButton2.setText("Print Transaksi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnSimpanTrx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/icon/pc.de-hamburg-icon-pack/16x16/project.png"))); // NOI18N
        btnSimpanTrx.setText("Simpan Transaksi");
        btnSimpanTrx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanTrxActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSimpanTrx)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpanTrx, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cmbUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(221, 238, 238));
        jPanel2.setPreferredSize(new java.awt.Dimension(781, 150));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setText("Total :");

        txttotalHarga.setEditable(false);
        txttotalHarga.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txttotalHarga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtDate.setEditable(false);
        txtDate.setSelectedTextColor(new java.awt.Color(242, 242, 242));

        txtuang.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtuang.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtuang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtuangKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtuangKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Uang :");

        txtKembali.setEditable(false);
        txtKembali.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtKembali.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setText("Kembali :");

        txtIdTrx.setEditable(false);
        txtIdTrx.setSelectedTextColor(new java.awt.Color(242, 242, 242));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtIdTrx, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtuang, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txttotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdTrx, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        tblKeranjang.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tblKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKeranjang.setRowHeight(25);
        tblKeranjang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblKeranjangKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblKeranjangKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblKeranjang);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(221, 238, 238));
        jPanel3.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel4.setBackground(new java.awt.Color(221, 238, 238));
        jPanel4.setPreferredSize(new java.awt.Dimension(30, 388));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblKeranjangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblKeranjangKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tblKeranjangKeyPressed

    private void tblKeranjangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblKeranjangKeyReleased

        int baris = tblKeranjang.getSelectedRow();

        String harga = tblKeranjang.getValueAt(baris, 2).toString();
        String banyaknya = tblKeranjang.getValueAt(baris, 3).toString();

        int total = Integer.parseInt(harga) * Integer.parseInt(banyaknya);

        tblKeranjang.setValueAt(total, baris, 4);

        int totalHarga = 0;
        for (int i = 0; i < tblKeranjang.getRowCount(); i++) {
            String totalbrg = tblKeranjang.getValueAt(i, 4).toString();
            int totalnya = Integer.parseInt(totalbrg);
            totalHarga += totalnya;
        }

        txttotalHarga.setText(String.valueOf(totalHarga));
    }//GEN-LAST:event_tblKeranjangKeyReleased

    private void txtuangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuangKeyPressed

    }//GEN-LAST:event_txtuangKeyPressed

    private void btnSimpanTrxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanTrxActionPerformed
        simpanTransaksi();
    }//GEN-LAST:event_btnSimpanTrxActionPerformed

    private void txtuangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuangKeyReleased
        int totalHarga = 0;
        for (int i = 0; i < tblKeranjang.getRowCount(); i++) {
            String totalbrg = tblKeranjang.getValueAt(i, 4).toString();
            int totalnya = Integer.parseInt(totalbrg);
            totalHarga += totalnya;
        }

        String uang = txtuang.getText();

        int kembali = Integer.parseInt(uang) - totalHarga;
        txtKembali.setText(String.valueOf(kembali));
    }//GEN-LAST:event_txtuangKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        simpanTransaksi();
        try{
            String file = "/home/mangg/NetBeansProjects/Printing-Store/src/store/report1.jrxml";
            
          
            HashMap param = new HashMap();
            
            for (int i = 0; i < tblKeranjang.getRowCount(); i++) {
                param.put("id_brg", "i");
            }
            param.put("kodetransaksi", txtIdTrx.getText());
            param.put("total", txttotalHarga.getText());
            param.put("uang", txtuang.getText());
            param.put("kembali", txtKembali.getText());
            param.put("tanggal", txtDate.getText());


            
            JasperReport JRpt = JasperCompileManager.compileReport(file);
            JasperPrint print = JasperFillManager.fillReport(JRpt,param,Koneksi.konekKeDB());
            JasperViewer.viewReport(print, false);
            
        }catch(JRException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(keranjangProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(keranjangProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(keranjangProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(keranjangProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                keranjangProduct dialog = new keranjangProduct(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpanTrx;
    private javax.swing.JComboBox<String> cmbUser;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTable tblKeranjang;
    private static javax.swing.JTextField txtDate;
    public javax.swing.JTextField txtIdTrx;
    private javax.swing.JTextField txtKembali;
    private javax.swing.JTextField txttotalHarga;
    private javax.swing.JTextField txtuang;
    // End of variables declaration//GEN-END:variables

    public void totalBarang() {
        int totalHarga = 0;
        for (int i = 0; i < tblKeranjang.getRowCount(); i++) {
            String totalbrg = tblKeranjang.getValueAt(i, 4).toString();
            int totalnya = Integer.parseInt(totalbrg);
            totalHarga += totalnya;
        }

        txttotalHarga.setText(String.valueOf(totalHarga));
    }

    public void putDate() {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();

        txtDate.setText(dtf.format(now));
    }

    public String getIdTransaksi() {
        String idtrx = "";
        try {
            Connection c = Koneksi.konekKeDB();
            Statement sti = c.createStatement();
            String query = "SELECT kode_tr FROM transactionQ ORDER BY kode_tr DESC LIMIT 1;";
            ResultSet rs = sti.executeQuery(query);
            while (rs.next()) {
                idtrx = rs.getString("kode_tr");
            }

            dispose();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

        return idtrx;
    }

    public void setAdmin() {
        try {
            Connection c = Koneksi.konekKeDB();
            Statement sti = c.createStatement();
            String query = "SELECT * FROM users;";
            ResultSet rs = sti.executeQuery(query);
            while (rs.next()) {
                String nama = rs.getString("nama");

                cmbUser.addItem(nama);
            }

            dispose();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void simpanTransaksi() {
        String total = txttotalHarga.getText();
        String uang = txtuang.getText();
        String kembali = txtKembali.getText();
        int user = cmbUser.getSelectedIndex() + 1;
        String date = txtDate.getText();

        try {
            Connection c = Koneksi.konekKeDB();
            Statement sti = c.createStatement();
            String query = "INSERT INTO transactionQ VALUES(NULL,NULL," + user + "," + total + "," + uang + "," + kembali + ",'" + date + "');";
            sti.executeUpdate(query);

            for (int i = 0; i < tblKeranjang.getRowCount(); i++) {
                String kodebarang = (String) tblKeranjang.getValueAt(i, 0);
                String qtybarang = (String) tblKeranjang.getValueAt(i, 3);
                String idQ = getIdTransaksi();

                Statement st2 = c.createStatement();
                String query2 = "INSERT INTO detail_transaction VALUES(NULL,'" + idQ + "','" + kodebarang + "'," + qtybarang + ");";
                st2.executeUpdate(query2);
            }

            c.close();
            JOptionPane.showMessageDialog(null, "Transaksi Berhasil di Simpan");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }
}
